server:
  port: 8000
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
#      - id: user-service
#        uri: lb://USER-SERVICE
#        predicates:
#        - Path=/user-service/**
        
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
          - Path=/user-service/**
          - Method=POST
        filters:
          - RemoveRequestHeader=Cookie
          # RewritePath는 user-service라는 것으로 요청할 때 앞의 url로 호출되었을 경우 뒤의 url로 변경.
          - RewritePath=/user-service/(?<segment>.*), /$\{segment}

      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
          - Path=/user-service/**
          - Method=GET
        filters:
          - RemoveRequestHeader=Cookie
          # RewritePath는 user-service라는 것으로 요청할 때 앞의 url로 호출되었을 경우 뒤의 url로 변경.
          - RewritePath=/user-service/(?<segment>.*), /$\{segment}
          - AuthorizationHeaderFilter

#      - id: user-service
#        uri: lb://USER-SERVICE
#        predicates:
#          - Path=/user-service/users
#          - Method=POST
#        filters:
#          - RemoveRequestHeader=Cookie
#          - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#
#      - id: user-service
#        uri: lb://USER-SERVICE
#        predicates:
#          - Path=/user-service/**
#          - Method=GET
#        filters:
#          - RemoveRequestHeader=Cookie
#          - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#        # 앞에 있는 url 형태로 들어올 경우 뒤의 형태로 변경.
        
      - id: catalog-service
        uri: lb://CATALOG-SERVICE
        predicates:
          - Path=/catalog-service/**
      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:
          - Path=/order-service/**
#      - id: first-service
#        uri: http://localhost:8081/first-service/**
#        predicates:
#        - Path=/first-service/**
#      - id: second-service
#        uri: http://localhost:8082/second-service/**
#        predicates:
#        - Path=/second-service/**
      
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
          - Path=/user-service/actuator/**
          - Method=GET, POST
        filters:
          - RemoveRequestHeader=Cookie
          # RewritePath는 user-service라는 것으로 요청할 때 앞의 url로 호출되었을 경우 뒤의 url로 변경.
          - RewritePath=/user-service/(?<segment>.*), /$\{segment}


#token:
#  secret: user_token

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace